{% set name = "python-ironicclient" %}
{% set version = "4.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-ironicclient-{{ version }}.tar.gz
  sha256: 99d45e914b2845731ac44fbfc63ae3e1bd52211396748797b588f2adc4b3f341

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pbr >=2.0.0
    - pip
  run:
    - python >=3.6
    - appdirs >=1.3.0
    - cliff !=2.9.0,>=2.8.0
    - dogpile.cache >=0.8.0
    - jsonschema >=3.2.0
    - keystoneauth1 >=3.11.0
    - openstacksdk >=0.18.0
    - osc-lib >=2.0.0
    - oslo.utils >=3.33.0
    - pbr !=2.1.0,>=2.0.0
    - pyyaml >=3.13
    - requests >=2.14.2
    - stevedore >=1.20.0

test:
  imports:
    - ironicclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.openstack.org/python-ironicclient/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Bindings to the OpenStack Ironic API
  dev_url: https://git.openstack.org/cgit/openstack/python-ironicclient

extra:
  recipe-maintainers:
    - brainstorm 
