{% set name = "python-ironicclient" %}
{% set version = "2.4.0" %}
{% set sha256 = "4fc01f7d0a4150d4d0dc53f4dcdd35ce8f41a61893330bb519dd62aeda7f10ac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr

  run:
    - python
    - pbr
    - keystoneauth1
    - oslo.utils
    - oslo.i18n
    - oslo.serialization
    - dogpile.cache
    - prettytable
    - appdirs
    - six

test:
  imports:
    - ironicclient
#  commands:
#    - ironic help
#    XXX:  cmdline seems broken upstream

about:
  home: https://docs.openstack.org/python-ironicclient/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Bindings to the OpenStack Ironic API
  dev_url: https://git.openstack.org/cgit/openstack/python-ironicclient

extra:
  recipe-maintainers:
    - brainstorm 
