appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LRfqqivXYNz7JBCpdmtsEHOG9k3f5H1+mwVm7WeuQmaSAJvFa5lgtECt2Sc85ZQppRTTt5B3QRfcU5oq7oU8u3kVVJghJIQQ3JDdNChgAYNMGRB2MItMejLik+4h3CDpmlFLC6ze3bwQ1Y5lQlC24NyNlFwx0hdFWUbKMdLZFdIHLidjVRMfwDyYCmYXnT/IHecIfHqYZr4NIl2gCdI6AMQx7yUMSGLbhRUuAGPGW0kpFgm9Q57seRSw5ANUY18JKmIC9b+d+AJqXbUvA41qCg3uAzuSVpHs/+G4vXqRN3CCOlVGUJX0qKuBSvz5k114YYbsTU/I8XynSd6o+qxKJLB1duKWbVtBta5qHrcc6kx6gIS7vVcfz7f8L9/Vzsc1beRYiPxgfSjhKAoLe4+3r/Kw4fxyauAZVdbbwU2spi98HT1n1kAUpRK4pViUKi6Lb8p0Rzrm1uG3BM/7+yDvPCRMqWM6EdKeni449sE7KNFMRJN9aWJAch2Gw5fETM0P+ItBO1GbAPcE6bCN0GhyxIufnfxZm1f9Vyol5e/Rp2GP4j2/wHJCwkvPNKH3AWxVvNy0R1vT7ssX/OxOeVKrSZfq55jByrTIvXZ7x9exw8FjJYERqHwXwQ3JfjbVAoWjBBnEaEf8FXDpOSTjMj/Wu+J9Wedfva+qHbHrPNh/X6A=}
provider:
  win: azure
bot:
  automerge: true
